spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hotel_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.use_nationalized_character_data=true
server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hotelmanagementcantho@gmail.com
spring.mail.password=gveg sgcx nfxt lwzf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mandatory-file-encoding=UTF-8

# Cấu hình UTF-8 cho Thymeleaf và HTTP Responses
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Cấu hình tải tệp tin
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cấu hình tài khoản nhận thanh toán VietQR
payment.bank-code=KLB
payment.bank-account=9614072005
payment.account-name=CHAU QUOC INH

# Cấu hình PayOS
payment.payos.client-id=b58f28ee-4d28-4630-a2cf-cada50131547
payment.payos.api-key=430d2c19-b4af-43ea-8c54-b683a5868fd1
payment.payos.checksum-key=7cf1f6461bf7d038f6bafe7d9ae09601131c89d7535840fc660b953a102260cc

# Cấu hình PayPal
payment.paypal.client-id=AeNAYOddyHU10q8mYVeN24titoNyvsUk1XarvZ48hfELk0Ucd-Dq9w-9bpBkAl5EMRC6EW1Odh6C0pq9
payment.paypal.client-secret=EOw2CMr1dkYnxm-Kc3_FomVav_9DwLdHSir1H1jR8r2abIRze9bC9LqYktIHwxcS_3rWPoi9kOOFjMIU
payment.paypal.mode=sandbox
payment.paypal.vnd-to-usd-rate=25400
payment.paypal.return-base-url=http://localhost:8082
